[workspace]
members = [
    # "mpc-recovery",
    "contract",
    "node",
    "integration-tests",
    # "integration-tests/chain-signatures",
    # "integration-tests/mpc-recovery",
    # "load-tests",
    "keys",
    "test-oidc-provider",
]

[profile.flamegraph]
inherits = "release"
debug = true
