[workspace]
members = [
    "mpc-recovery",
    "integration-tests",
]

[patch.crates-io]
bollard = { path = "bollard" }
hyper = { path = "hyper" }
hyperlocal = { path = "hyperlocal" }
tokio = { path = "tokio/tokio" }
mio = { path = "mio" }
