[package]
name = "mpc-recovery-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
anyhow = "1.0"
bollard = "0.11"
futures = "0.3"
hex = "0.4"
hyper = { version = "0.14", features = ["full"] }
mpc-recovery = { path = "../mpc-recovery" }
near-crypto = "0.16.1"
near-units = "0.2.0"
once_cell = "1"
portpicker = "0.1"
rand = "0.8"
serde = "1"
serde_json = "1"
testcontainers = { version = "0.14", features = ["experimental"] }
tokio = { version = "1.0", features = ["full"] }
workspaces = { git = "https://github.com/near/workspaces-rs", branch = "main" }
curv = { package = "curv-kzen", version = "0.9", default-features = false }
ed25519-dalek = {version = "1.0.1", features = ["serde"]}
multi-party-eddsa = { git = "https://github.com/DavidM-D/multi-party-eddsa.git", rev = "25ae4fdc5ff7819ae70e73ab4afacf1c24fc4da1" }
reqwest = "0.11.16"

[features]
drop-containers = []
default = ["drop-containers"]
