[package]
name = "mpc-recovery-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
anyhow = "1.0"
bollard = "0.14"
ed25519-dalek = "1"
futures = "0.3"
hex = "0.4"
hyper = { version = "0.14", features = ["full"] }
mpc-recovery = { path = "../mpc-recovery" }
near-crypto = "0.16.1"
once_cell = "1"
portpicker = "0.1"
rand = "0.8"
serde = "1"
serde_json = "1"
threshold_crypto = "0.4.0"
tokio = { version = "1.0", features = ["full"] }
workspaces = { git = "https://github.com/near/workspaces-rs", branch = "main" }
