[package]
name = "mpc-recovery-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aes-gcm = "0.10"
anyhow = { version = "1.0", features = ["backtrace"] }
bollard = "0.11"
clap = { version = "4.2", features = ["derive", "env"] }
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
futures = "0.3"
hex = "0.4.3"
hyper = { version = "0.14", features = ["full"] }
mpc-recovery = { path = "../mpc-recovery" }
multi-party-eddsa = { git = "https://github.com/DavidM-D/multi-party-eddsa.git", rev = "25ae4fdc5ff7819ae70e73ab4afacf1c24fc4da1" }
tracing = "0.1"
near-crypto = "0.17"
near-jsonrpc-client = "0.6"
near-primitives = "0.17"
near-units = "0.2.0"
once_cell = "1"
serde = "1"
serde_json = "1"
testcontainers = { version = "0.14", features = ["experimental"] }
tokio = { version = "1.28", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
near-workspaces = { git = "https://github.com/near/workspaces-rs", branch = "main" }
toml = "0.8.1"

[dev-dependencies]
rand = "0.7"
rand8 = { package = "rand", version = "0.8" }
test-log = { version = "0.2.12", features = ["log", "trace"] }
env_logger = "0.10.0"
tracing-log = "0.1.3"
tokio-util = { version = "0.7", features = ["full"] }
curv = { package = "curv-kzen", version = "0.9", default-features = false }
reqwest = "0.11.16"

[features]
drop-containers = []
default = ["drop-containers"]
