name: Integration
on:
  push:
    branches:
      - main
      - develop
  pull_request:
env:
  RUSTFLAGS: -D warnings
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install docker
          colima start
          # 
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Relayer Docker Image
        run: |
          docker pull ghcr.io/near/pagoda-relayer-rs-fastauth
          docker pull ghcr.io/near/sandbox
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: near/mpc-recovery:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test
        run: cargo test -p mpc-recovery-integration-tests --jobs 1 -- --test-threads 1
        env:
          RUST_LOG: INFO
          RUST_BACKTRACE: 1