name: Integration tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
env:
  RUSTFLAGS: -D warnings
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'near/pagoda-relayer-rs-fastauth'
          ref: 'daniyar/custom-entrypoint'
          path: 'relayer'
          ssh-key: ${{ secrets.RELAYER_DEPLOY_SSH_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: relayer
          tags: pagoda-relayer-rs-fastauth
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: near/mpc-recovery:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test
        run: cargo test -p mpc-recovery-integration-tests --jobs 1 -- --test-threads 1
