name: Deploy Multichain Prod.
on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        options:
          - mainnet
          - testnet
        description: mainnet or testnet network
        required: true
      image:
        description: Full Artifact Registry image with tag (e.g. us-east1-docker.pkg.dev/pagoda-discovery-platform-prod/multichain/multichain-< testnet | mainnet >)
        required: true
      tag:
        description: Image tag that you wish to deploy, either by SHA or Version/latest
      node_group:
        type: choice
        options:
          - partner
          - internal
        description: Do you want to deploy the Parner nodes or internal Pagoda nodes?

jobs:
  build-mpc-recovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Checkout mpc-recovery"

      - name: Login to GCP Artifact Registry
        run: echo "$GOOGLE_CREDENTIALS" | docker login -u _json_key --password-stdin https://us-east1-docker.pkg.dev
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_PROD }}

      - name: Build Docker image and push to internal Google Artifact Registry
        if: ${{ github.event.inputs.node_group == 'internal' }}
        id: docker-push-tagged
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile.multichain
          tags: "${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}"
      
      - name: Build Docker image and deploy partner nodes
        if: ${{ github.event.inputs.node_group == 'partner' }}
        id: docker-push-tagged-partner
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile.multichain
          tags: "${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}"

  deploy:
    if: ${{ github.event.inputs.node_group == 'internal' }}
    runs-on: ubuntu-latest
    needs: build-mpc-recovery
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_PROD }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: 'Set project'
        run: 'gcloud config set project pagoda-discovery-platform-prod'

      - name: 'Update Nodes'
        run: |
          gcloud compute instances update-container multichain-${{ github.event.inputs.network }}-0 --zone us-central1-a --container-image=${{ github.event.inputs.image }}:${{ github.event.inputs.tag }} & \
          gcloud compute instances update-container multichain-${{ github.event.inputs.network }}-1 --zone us-central1-a --container-image=${{ github.event.inputs.image }}:${{ github.event.inputs.tag }} & \
          gcloud compute instances update-container multichain-${{ github.event.inputs.network }}-2 --zone us-central1-a --container-image=${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}

