name: Unit
on:
  push:
    branches:
      - main
      - develop
  pull_request:
env:
  RUSTFLAGS: -D warnings
jobs:
  test:
    runs-on: ubuntu-latest
    name: Check & Test
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile Contract
        run: cargo build -p mpc-contract --target wasm32-unknown-unknown --release --target-dir target/seperate_wasm
      - name: Compile
        run: cargo check
      - name: Test format
        run: |
          ( cd keys ; cargo fmt -- --check )
          ( cd node ; cargo fmt -- --check )
          ( cd contract ; cargo fmt -- --check )
          ( cd mpc-recovery ; cargo fmt -- --check )
          ( cd load-tests/ ; cargo fmt -- --check )
          ( cd test-oidc-provider/ ; cargo fmt -- --check )
          ( cd integration-tests/chain-signatures ; cargo fmt -- --check )
          ( cd integration-tests/fastauth ; cargo fmt -- --check )

      - name: Unit tests
        run: ( cd mpc-recovery && cargo test )
      - name: Test clippy
        run: |
          ( cd keys ; cargo clippy --tests -- -Dclippy::all )
          ( cd node ; cargo clippy --tests -- -Dclippy::all )
          ( cd contract ; cargo clippy --tests -- -Dclippy::all )
          ( cd mpc-recovery ; cargo clippy --tests -- -Dclippy::all )
          ( cd load-tests/ ; cargo clippy --tests -- -Dclippy::all )
          ( cd test-oidc-provider/ ; cargo clippy --tests -- -Dclippy::all )
          ( cd integration-tests/chain-signatures ; cargo clippy --tests -- -Dclippy::all )
          ( cd integration-tests/fastauth ; cargo clippy --tests -- -Dclippy::all )

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Install Audit
        run: cargo install cargo-audit
      - name: Run Audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
          args: --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2023-0052 --ignore RUSTSEC-2022-0093 --ignore RUSTSEC-2023-0071 --ignore RUSTSEC-2024-0019
