name: Unit
on:
  push:
    branches:
      - main
      - develop
  pull_request:
env:
  RUSTFLAGS: -D warnings
jobs:
  test:
    runs-on: ubuntu-latest
    name: Check & Test
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
      - name: Compile
        run: cargo check
      - name: Test format
        run: cargo fmt -- --check
      - name: Unit tests
        run: cargo test -p mpc-recovery
      - name: Test clippy
        run: cargo clippy --tests -- -Dclippy::all
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Install Audit
        run: cargo install cargo-audit
      - name: Run Audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
          # Fix RUSTSEC-2023-0001 by upgrading tokio once https://github.com/near/nearcore/issues/8888 is resolved
          args: --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2023-0001
